alert("I'am Javascript");
let name;
let admin;
name = "John";
admin = name;
alert(admin);
const ourPlanetName = "Earth";
alert(ourPlanetName);
var currentUserName= "Sanjay";
alert(currentUserName);
const BIRTHDAY = "27.10.2022"; 
const age = someCode(BIRTHDAY);